dvorskyi_KR/app/library_reader/models.py
from .. import db
import enum


class FormsStudyType(enum.Enum):
    Eye = 'Eye'
    Correspondence = 'Correspondence'
    Dual = 'Dual'


class Reader(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(30), unique=False, nullable=False)
    last_name = db.Column(db.String(30), unique=False, nullable=False)
    form_study_type = db.Column(db.Enum(FormsStudyType))
    email = db.Column(db.String(40), unique=False, nullable=False)
    book_title = db.Column(db.String(50), unique=False, nullable=False)
    date_issue = db.Column(db.DateTime, default=db.func.now())

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

dvorskyi_KR/app/library_reader/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import InputRequired, Length, Regexp


class ReaderFormCreate(FlaskForm):
    first_name = StringField('First name', validators=[InputRequired('A first name is required'),
                                                     Length(min=1, max=25, message='Name must have greater 4 '
                                                                                   'symbol and least 25 symbol'),
                                                     Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                            'Username must have only letters, numbers, '
                                                            'dots or underscores')])

    last_name = StringField('Last name', validators=[InputRequired('A last name is required'),
                                                    Length(min=1, max=25, message='Name must have greater 4 '
                                                                                  'symbol and least 25 symbol'),
                                                    Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                           'Username must have only letters, numbers, '
                                                           'dots or underscores')])

    email = StringField('Email', validators=[InputRequired('Email is required'),
                                             Regexp('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$',
                                                    message='Invalid Email')])

    form_study_type = SelectField('Form study type',
                                  choices=[('Eye', 'Eye'), ('Correspondence', 'Correspondence'), ('Dual', 'Dual')])

    book_title = StringField('Book title', validators=[InputRequired(), Length(min=2, max=60)])

dvorskyi_KR/app/library_reader/__init__.py
from flask import Blueprint

library_blueprint = Blueprint('lib', __name__, template_folder="templates/library_reader")

from . import views

dvorskyi_KR/app/library_reader/views.py
from flask import redirect, render_template, url_for, flash, abort
from . import library_blueprint
from flask_login import login_required, current_user, login_user, logout_user
from .. import db
from .forms import ReaderFormCreate
from .models import Reader


@library_blueprint.route("/create", methods=['GET', 'POST'])
@login_required
def create_reader():
    form = ReaderFormCreate()
    if form.validate_on_submit():
        reader = Reader(first_name=form.first_name.data, last_name=form.last_name.data,
                        form_study_type=form.form_study_type.data, email=form.email.data,
                        book_title=form.book_title.data, user_id=current_user.id)

        db.session.add(reader)
        db.session.commit()

        return redirect(url_for('lib.detail_reader', id=reader.id))

    return render_template('form_readers.html', form=form)


@library_blueprint.route("/", methods=['GET', 'POST'])
def readers():
    readers_lib = Reader.query.all()
    return render_template('readers.html', readers=readers_lib)


@library_blueprint.route("/detail/<id>", methods=['GET', 'POST'])
def detail_reader(id):
    reader = Reader.query.get_or_404(id)
    return render_template('detail_readers.html', reader=reader)


@library_blueprint.route('/delete/<id>', methods=['GET', 'POST'])
@login_required
def delete_reader(id):
    reader = Reader.query.get_or_404(id)
    if current_user.id == reader.user_id:
        db.session.delete(reader)
        db.session.commit()
        return redirect(url_for('lib.readers'))

    flash('This is not your post', category='warning')
    return redirect(url_for('lib.detail_reader', id=id))


@library_blueprint.route('/update/<id>', methods=['GET', 'POST'])
@login_required
def update_reader(id):
    reader = Reader.query.get_or_404(id)
    if current_user.id != reader.user_id:
        flash('This is not your post', category='warning')
        return redirect(url_for('lib.detail_reader', id=reader.id))

    form = ReaderFormCreate()

    if form.validate_on_submit():
        reader.first_name = form.first_name.data
        reader.last_name = form.last_name.data
        reader.form_study_type = form.form_study_type.data
        reader.email = form.email.data
        reader.book_title = form.book_title.data

        db.session.add(reader)
        db.session.commit()

        flash('Institution has been update', category='access')
        return redirect(url_for('lib.detail_reader', id=id))

    form.first_name.data = reader.first_name
    form.last_name.data = reader.last_name
    form.form_study_type.data = reader.form_study_type
    form.email.data = reader.email
    form.book_title.data = reader.book_title

    return render_template('form_readers.html', form=form)

dvorskyi_KR/app/library_reader/templates/library_reader/detail_readers.html
{% extends 'main.html' %}
{% from "_render_field.html" import render_field %}

{% block title %}
<title>Sign Up</title>
<style>
    .title {
        color: white;
    }

    .block {
        background-color: darkcyan;
        color: white;
    }

    .button {
        color: white;
        padding: 5px 20px;
        background-color: black;
    }

    a {
        color: white
    }

</style>
{% endblock %}

{% block content %}

<form class="centered bg-color block" method="POST">
    <h1 class="title">Reader info</h1>
    <p>First name: {{ reader.first_name }}</p>
    <p>Last name: {{ reader.last_name }}</p>
    <p>Type study: {{ reader.form_study_type }}</p>
    <p>Email: {{ reader.email }}</p>
    <p>Book title: {{ reader.book_title }}</p>
    <p>Date issue: {{ reader.date_issue }}</p>
    <p>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
        <a href="{{ url_for('lib.update_reader', id=reader.id) }}" type="submit">edit</a>
    </p>
</form>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete reader</h5>
                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete the reader?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('lib.delete_reader', id=reader.id) }}" method="POST"> <!-- delete !-->
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dvorskyi_KR/app/library_reader/templates/library_reader/form_readers.html
{% extends 'main.html' %}
{% from "_render_field.html" import render_field %}

{% block title %}
<title>Sign Up</title>
<style>
    .title {
        color: white;
    }

    .block {
        background-color: darkcyan;
        color: white;
    }

    .button {
        color: white;
        padding: 5px 20px;
        background-color: black;
    }
</style>
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}



<form class="centered bg-color block" method="POST">
    <h1 class="title">Create Reader</h1>
    {{ form.csrf_token }}
    {{ render_field(form.first_name) }}
    {{ render_field(form.last_name) }}
    {{ render_field(form.email) }}
    {{ render_field(form.form_study_type) }}
    {{ render_field(form.book_title) }}
    <button class="button">Create</button>
</form>
{% endblock %}

dvorskyi_KR/app/library_reader/templates/library_reader/readers.html
{% extends 'main.html' %}
{% from "_render_field.html" import render_field %}

{% block title %}
<title>Sign Up</title>
<style>
    .block {
        display: flex;
        flex-flow: row wrap;
        align-items: center;
    }

    .item {
        width: 300px;
        height: 300px;
        border: 1px solid black;
        margin: 80px 20px 80px 20px;
        border-radius: 10px;
        background-color: darkcyan;
        color: white;
    }

a {
    color: white;
}

</style>
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="block">
    {% for reader in readers %}
    <div class="item">
        <h1><a href="{{ url_for('lib.detail_reader', id=reader.id) }}">{{ reader.first_name }} {{ reader.last_name }}</a></h1>
        Книга
        <p>{{ reader.book_title }}</p>
        <p>{{ reader.date_issue }}</p>
    </div>
    {% endfor %}


</div>

{% endblock %}