lab13/app/form_cabinet/__init__.py
from flask import Blueprint, render_template, flash, session, redirect, url_for
from .forms import DataForm, Form
from .function import validations, write_json
import json

cabinet_blueprint = Blueprint('cabinet', __name__, template_folder="templates/form_cabinet")

# Lab4
@cabinet_blueprint.route("/form", methods=['GET', 'POST'])
def form():
    form = Form()
    flash('password is password or secret')
    if form.validate_on_submit():
        return f'The username is {form.username.data}. The password is {form.password.data}'

    return render_template('form.html', form_f=form)


# lab5-6
@cabinet_blueprint.route("/register_cabinet", methods=['GET', 'POST'])
def register_cabinet():

    form = DataForm()
    validations(form)
    if form.validate_on_submit():
        session['email'] = form.email.data
        write_json(form)
        flash('User has been written in json file')
        return redirect(url_for('cabinet.register_cabinet'))

    try:
        sesiya = session['email']

    except:
        return render_template('start.html', form=form)

    with open('data.json') as f:
        data_files = json.load(f)

    form.email.data = session['email']
    form.number.data = data_files[sesiya]['number']
    form.pin.data = data_files[sesiya]['pin']
    form.year.data = data_files[sesiya]['year']
    form.serial.data = data_files[sesiya]['serial']
    form.number.data = data_files[sesiya]['number_doc']

    return render_template('start.html', form=form)

lab13/app/main_bp/__init__.py
from flask import render_template, request, Blueprint
import os, sys, platform
from datetime import datetime

main_bp = Blueprint('main_bp', __name__, template_folder="templates/main_bp")


# Lab3
@main_bp.route("/blog")
def blog():
    news_dict = {
        'first day': 'I feel good',
        'Second Day': 'I feel bad',
        'Third Day': 'I happy',

    }
    return render_template("blog.html", news_dict=news_dict, sys_info=request.headers.get('User-Agent'),
                           sys=sys.version, os_name=os.name, platform=platform.system(), release=platform.release(),
                           date=datetime.now())


@main_bp.route("/news")
def news():
    news_dict = {
        'I start study Django': 'ok',
        'Okay': 'Today nice weather',
        'tomorow': 'I walk to university',

    }
    return render_template("news.html", news_dict=news_dict, sys_info=request.headers.get('User-Agent'),
                           sys=sys.version, os_name=os.name, platform=platform.system(), release=platform.release(),
                           date=datetime.now())


@main_bp.route("/")
def portfolio():
    return render_template("personal_portfolio.html", boolean=False, name='Nazar', error='Wrong data',
                           sys_info=request.headers.get('User-Agent'), sys=sys.version, os_name=os.name,
                           platform=platform.system(), release=platform.release(), date=datetime.now())


@main_bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html')

lab13/app/templates/_render_field.html
{% macro render_field(field) %}
{{ field.label }}
{{ field(**kwargs)|safe }}
<ul>
    {% for error in field.errors %}
        <li style="color:red;">{{ error }}</li>
    {% endfor %}
</ul>
{% endmacro %}

lab13/app/templates/base.html
<!DOCTYPE html>
<head>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<html>
<body>
{% include 'nav.html' %}

{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
<div class="container">
    {% for category, message in messages %}
    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

{% block content %}
{% endblock %}




<footer class="footer fixed-bottom text-center">
    {% block footer %}
    {% endblock %}
</footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

</body>
</html>

lab13/app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main_bp.portfolio') }}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('main_bp.news') }}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main_bp.blog') }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('cabinet.form') }}">Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('cabinet.register_cabinet') }}">Registers Cabinet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.users') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('post.view_post') }}">Posts</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('post.create') }}">Create Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.account') }}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">SignUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>