lab12/app/doc_registration/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectField
from wtforms.validators import InputRequired, Length, AnyOf, Regexp, EqualTo


class Form(FlaskForm):
    username = StringField('username', validators=[InputRequired('A username is required'),
                                                   Length(min=5, max=10,
                                                          message='Username length must be in range 5-10')])
    password = PasswordField('password', validators=[InputRequired('Password is required'),
                                                     AnyOf(values=['password', 'secret'])])


class DocRegistration(FlaskForm):
    email = StringField('Email*', validators=[InputRequired('Email is required'),
                                              Regexp('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'),
                                              Length(min=5, max=30, message='Email must be correct')])
    password = PasswordField('Password*', validators=[InputRequired('Password is required'),
                                                      Length(min=6, message='Must be at least 6')])
    confirm_password = PasswordField('Confirm password*', validators=[InputRequired('Password is required'),
                                                                      Length(min=6,
                                                                             message='Passwords must be the same'),
                                                                      EqualTo('password')])
    number = StringField('Number*', validators=[InputRequired('Number is required'),
                                                Length(min=7, max=7, message='The length must be exactly 7')])
    pin = StringField('PIN code*', validators=[InputRequired('Pin code is required'),
                                               Regexp('[0-9]{4}', message='Must be 4 digits of the PIN code'),
                                               Length(min=4, max=4)])
    year = SelectField('Year *', choices=[2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])
    serial = StringField('Serial number')
    doc_number = StringField('Document number*')

lab12/app/doc_registration/__init__.py
from flask import Blueprint

doc_registration_blueprint = Blueprint('doc_registration', __name__, template_folder="templates")

from . import views

lab12/app/doc_registration/views.py
import json

from flask import render_template, flash, session, redirect, url_for

from . import doc_registration_blueprint
from .forms import Form, DocRegistration
from ..controller import validate_fields, json_data, user_info


@doc_registration_blueprint.route("/form", methods=['GET', 'POST'])
def form():
    form = Form()
    flash('Password value must be --> password or secret')
    if form.validate_on_submit():
        return f'<h1>The username is {form.username.data}. The password is {form.password.data}</h1>'
    return render_template('form.html', form=form, user_info=user_info())


@doc_registration_blueprint.route("/doc_registration", methods=['GET', 'POST'])
def doc_registration():
    doc_reg = DocRegistration()
    validate_fields(doc_reg)

    if doc_reg.validate_on_submit():
        session['email'] = doc_reg.email.data
        json_data(doc_reg)
        flash('Data successfully added to json')
        return redirect(url_for('doc_registration.doc_registration'))

    try:
        session_data = session['email']
        with open('data.json') as file:
            data = json.load(file)

        return render_template('doc_registration.html', doc_reg=doc_reg, email=session_data,
                               number=data[session_data]['number'], pin=data[session_data]['pin'],
                               year=data[session_data]['year'], serial=data[session_data]['serial'],
                               doc_number=data[session_data]['doc_number'])
    except KeyError:
        return render_template('doc_registration.html', doc_reg=doc_reg)

lab12/app/doc_registration/templates/doc_registration.html
{% extends 'main.html' %}
{% from "_render_field.html" import render_field %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<form method="POST" class="form">
    {{ doc_reg.csrf_token }}
    {{ render_field(doc_reg.email, value=email) }}
    {{ render_field(doc_reg.password) }}
    {{ render_field(doc_reg.confirm_password) }}
    {{ render_field(doc_reg.number, value=number) }}
    {{ render_field(doc_reg.year, value=year) }}
    {{ render_field(doc_reg.pin, value=pin) }}
    {{ render_field(doc_reg.serial, value=serial) }}
    {{ render_field(doc_reg.doc_number, value=doc_number) }}
    <button>Submit</button>
</form>

{% endblock %}

lab12/app/doc_registration/templates/form.html
{% extends 'main.html' %}
{% from "_render_field.html" import render_field %}

{% block content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    {{ message }}
</div>
{% endfor %}

<form method="POST" action="{{ url_for('doc_registration.form') }}" class="form-control text-center">
    {{ form.csrf_token }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    <button>Submit</button>
</form>
{% endblock %}

{% block footer %}
{% for key, value in user_info.items() %}
<p>{{ key }} ---> {{ value }}</p>
{% endfor %}
{% endblock %}